modLoader = "kotlinforforge"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "fixedstarterivs"
version = "1.5-forge-1.0.0"
displayName = "Cobblemon Fixed Starter IVs"
description = '''
Quick and simple mod to set the IVs for starters to a fixed value.
'''

[[dependencies.fixedstarterivs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.fixedstarterivs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fixedstarterivs]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.5.0,1.6.0)"
ordering = "NONE"
side = "BOTH"
